import type { SOC2Control } from "@/types/soc2";

export const SOC2_CONTROLS: SOC2Control[] = [
  // ─── CC1 — Control Environment ─────────────────────────────────────────────
  {
    id: "CC1.1",
    category: "CC1",
    categoryName: "Control Environment",
    title: "COSO Principle 1: Demonstrates Commitment to Integrity and Ethical Values",
    description: "The entity demonstrates a commitment to integrity and ethical values.",
    guidance: "Create a Code of Conduct and get all employees to acknowledge it. Store acknowledgments as evidence.",
    commonEvidence: ["Code of Conduct document", "Employee acknowledgment records", "Ethics training completion records"],
    relatedPolicies: ["acceptable_use", "employee_security"],
    difficulty: "low",
    estimatedHours: 2,
  },
  {
    id: "CC1.2",
    category: "CC1",
    categoryName: "Control Environment",
    title: "COSO Principle 2: Board Independence and Oversight",
    description: "The board of directors demonstrates independence from management and exercises oversight of internal controls.",
    guidance: "Document your leadership structure, board/advisor roles, and governance meetings. Even as a startup, a simple org chart and advisory structure works.",
    commonEvidence: ["Org chart", "Board/advisor bios", "Meeting minutes or notes"],
    relatedPolicies: ["acceptable_use"],
    difficulty: "low",
    estimatedHours: 2,
  },
  {
    id: "CC1.3",
    category: "CC1",
    categoryName: "Control Environment",
    title: "COSO Principle 3: Management Structure, Reporting Lines",
    description: "Management establishes structures, reporting lines, and authorities and responsibilities in pursuit of objectives.",
    guidance: "Document your team structure with roles and responsibilities. Define who owns security decisions.",
    commonEvidence: ["Org chart with roles", "Job descriptions", "Security responsibility matrix"],
    relatedPolicies: ["acceptable_use", "employee_security"],
    difficulty: "low",
    estimatedHours: 3,
  },
  {
    id: "CC1.4",
    category: "CC1",
    categoryName: "Control Environment",
    title: "COSO Principle 4: Commitment to Competence",
    description: "The entity demonstrates a commitment to attract, develop, and retain competent individuals.",
    guidance: "Maintain records of employee hiring (background checks), onboarding, and security training.",
    commonEvidence: ["Hiring policy", "Background check records", "Security training records", "Onboarding checklist"],
    relatedPolicies: ["employee_security"],
    difficulty: "medium",
    estimatedHours: 4,
  },
  {
    id: "CC1.5",
    category: "CC1",
    categoryName: "Control Environment",
    title: "COSO Principle 5: Accountability",
    description: "The entity holds individuals accountable for their internal control responsibilities.",
    guidance: "Define clear accountability in policies. Track policy violations and disciplinary procedures.",
    commonEvidence: ["Acceptable use policy with disciplinary clauses", "Performance review process", "Incident accountability records"],
    relatedPolicies: ["acceptable_use", "employee_security"],
    difficulty: "low",
    estimatedHours: 2,
  },

  // ─── CC2 — Communication and Information ────────────────────────────────────
  {
    id: "CC2.1",
    category: "CC2",
    categoryName: "Communication and Information",
    title: "COSO Principle 13: Uses Relevant Information",
    description: "The entity obtains or generates and uses relevant, quality information to support internal control.",
    guidance: "Document how you collect and process security-relevant information (logs, alerts, monitoring).",
    commonEvidence: ["Monitoring setup documentation", "Log retention policy", "Security alert runbook"],
    relatedPolicies: ["incident_response"],
    difficulty: "medium",
    estimatedHours: 4,
  },
  {
    id: "CC2.2",
    category: "CC2",
    categoryName: "Communication and Information",
    title: "COSO Principle 14: Communicates Internally",
    description: "The entity internally communicates information necessary to support internal controls.",
    guidance: "Document how security policies and updates are communicated to the team (Slack, email, all-hands).",
    commonEvidence: ["Internal communication records", "Security briefing notes", "Slack channel for security"],
    relatedPolicies: ["acceptable_use"],
    difficulty: "low",
    estimatedHours: 2,
  },
  {
    id: "CC2.3",
    category: "CC2",
    categoryName: "Communication and Information",
    title: "COSO Principle 15: Communicates Externally",
    description: "The entity communicates with external parties regarding security commitments.",
    guidance: "Maintain a public security page, privacy policy, and responsible disclosure process.",
    commonEvidence: ["Security/trust page URL", "Privacy policy", "Responsible disclosure policy"],
    relatedPolicies: ["data_classification"],
    difficulty: "low",
    estimatedHours: 3,
  },

  // ─── CC3 — Risk Assessment ──────────────────────────────────────────────────
  {
    id: "CC3.1",
    category: "CC3",
    categoryName: "Risk Assessment",
    title: "COSO Principle 6: Specifies Suitable Objectives",
    description: "The entity specifies objectives with sufficient clarity to enable identification of risks.",
    guidance: "Document your security objectives. Tie them to your product roadmap and compliance goals.",
    commonEvidence: ["Security objectives document", "Risk assessment policy"],
    relatedPolicies: ["risk_assessment"],
    difficulty: "medium",
    estimatedHours: 4,
  },
  {
    id: "CC3.2",
    category: "CC3",
    categoryName: "Risk Assessment",
    title: "COSO Principle 7: Identifies and Analyzes Risk",
    description: "The entity identifies risks to achieving its objectives and analyzes them as a basis for risk management.",
    guidance: "Create a formal risk register. Identify threats to your infrastructure, data, and operations.",
    commonEvidence: ["Risk register", "Risk assessment report", "Threat model"],
    relatedPolicies: ["risk_assessment"],
    difficulty: "high",
    estimatedHours: 8,
  },
  {
    id: "CC3.3",
    category: "CC3",
    categoryName: "Risk Assessment",
    title: "COSO Principle 8: Assesses Fraud Risk",
    description: "The entity considers the potential for fraud in assessing risks to achieving objectives.",
    guidance: "Include fraud scenarios in your risk assessment. Consider insider threats, account takeover, data theft.",
    commonEvidence: ["Fraud risk assessment", "Access review records"],
    relatedPolicies: ["risk_assessment", "access_control"],
    difficulty: "medium",
    estimatedHours: 4,
  },
  {
    id: "CC3.4",
    category: "CC3",
    categoryName: "Risk Assessment",
    title: "COSO Principle 9: Identifies and Analyzes Change",
    description: "The entity identifies and assesses significant changes that could impact internal controls.",
    guidance: "Track changes to your tech stack, team, and architecture that could affect security posture.",
    commonEvidence: ["Change log", "Security impact assessments for major changes"],
    relatedPolicies: ["change_management", "risk_assessment"],
    difficulty: "medium",
    estimatedHours: 3,
  },

  // ─── CC4 — Monitoring Activities ────────────────────────────────────────────
  {
    id: "CC4.1",
    category: "CC4",
    categoryName: "Monitoring Activities",
    title: "COSO Principle 16: Conducts Ongoing Evaluations",
    description: "The entity selects and develops ongoing evaluations to monitor internal controls.",
    guidance: "Set up automated monitoring: uptime checks, security alerts, dependency scanning. Review monthly.",
    commonEvidence: ["Monitoring dashboard screenshots", "Alert configuration", "Monthly security review notes"],
    relatedPolicies: ["incident_response"],
    difficulty: "medium",
    estimatedHours: 6,
  },
  {
    id: "CC4.2",
    category: "CC4",
    categoryName: "Monitoring Activities",
    title: "COSO Principle 17: Evaluates and Communicates Deficiencies",
    description: "The entity evaluates and communicates control deficiencies in a timely manner.",
    guidance: "Have a process for identifying, reporting, and remediating security gaps. Track remediation in a ticket system.",
    commonEvidence: ["Deficiency tracking records", "Remediation evidence", "Security review meeting notes"],
    relatedPolicies: ["incident_response", "risk_assessment"],
    difficulty: "medium",
    estimatedHours: 4,
  },

  // ─── CC5 — Control Activities ────────────────────────────────────────────────
  {
    id: "CC5.1",
    category: "CC5",
    categoryName: "Control Activities",
    title: "COSO Principle 10: Selects and Develops Control Activities",
    description: "The entity selects and develops control activities that mitigate risks.",
    guidance: "Map your security controls to identified risks. Document why each control was chosen.",
    commonEvidence: ["Control mapping document", "Risk-to-control matrix"],
    relatedPolicies: ["risk_assessment"],
    difficulty: "medium",
    estimatedHours: 5,
  },
  {
    id: "CC5.2",
    category: "CC5",
    categoryName: "Control Activities",
    title: "COSO Principle 11: Selects General Technology Controls",
    description: "The entity selects and develops general technology controls to support objectives.",
    guidance: "Document your technical controls: MFA, encryption, WAF, vulnerability scanning, dependency updates.",
    commonEvidence: ["MFA enforcement screenshot", "Encryption configuration", "Vulnerability scan report"],
    relatedPolicies: ["access_control", "password_policy"],
    difficulty: "medium",
    estimatedHours: 6,
  },
  {
    id: "CC5.3",
    category: "CC5",
    categoryName: "Control Activities",
    title: "COSO Principle 12: Deploys Control Activities Through Policies",
    description: "The entity deploys control activities through policies and procedures.",
    guidance: "Ensure all security controls are documented in policies and employees are trained on them.",
    commonEvidence: ["Policy acknowledgment records", "Training completion records"],
    relatedPolicies: ["acceptable_use", "employee_security"],
    difficulty: "low",
    estimatedHours: 3,
  },

  // ─── CC6 — Logical and Physical Access Controls ──────────────────────────────
  {
    id: "CC6.1",
    category: "CC6",
    categoryName: "Logical and Physical Access Controls",
    title: "Logical Access Security Software, Infrastructure, and Architectures",
    description: "The entity implements logical access security software, infrastructure, and architectures.",
    guidance: "Enforce MFA on all critical systems (GitHub, AWS, Google, Clerk). Use SSO where available. Document all access points.",
    commonEvidence: ["MFA enforcement policy", "SSO configuration screenshots", "Access control policy"],
    relatedPolicies: ["access_control", "password_policy"],
    difficulty: "medium",
    estimatedHours: 6,
  },
  {
    id: "CC6.2",
    category: "CC6",
    categoryName: "Logical and Physical Access Controls",
    title: "New Internal and External Users, and Changes to User Access",
    description: "The entity manages logical access for new and existing users.",
    guidance: "Document your user provisioning and deprovisioning process. Have a checklist for onboarding/offboarding.",
    commonEvidence: ["User provisioning SOP", "Offboarding checklist", "Access review records"],
    relatedPolicies: ["access_control"],
    difficulty: "medium",
    estimatedHours: 4,
  },
  {
    id: "CC6.3",
    category: "CC6",
    categoryName: "Logical and Physical Access Controls",
    title: "Internal Access to Confidential/Sensitive Information",
    description: "The entity manages internal access to confidential information based on need-to-know.",
    guidance: "Implement role-based access control. Audit who has access to production systems and customer data quarterly.",
    commonEvidence: ["RBAC documentation", "Access review screenshots", "Least privilege policy"],
    relatedPolicies: ["access_control", "data_classification"],
    difficulty: "medium",
    estimatedHours: 5,
  },
  {
    id: "CC6.4",
    category: "CC6",
    categoryName: "Logical and Physical Access Controls",
    title: "Restricts Access to Confidential Information",
    description: "The entity restricts physical access to facilities and systems.",
    guidance: "If remote-first, document your remote work security policy. For offices, document physical access controls.",
    commonEvidence: ["Remote work policy", "Physical access policy", "VPN configuration"],
    relatedPolicies: ["access_control"],
    difficulty: "low",
    estimatedHours: 2,
  },
  {
    id: "CC6.5",
    category: "CC6",
    categoryName: "Logical and Physical Access Controls",
    title: "Discontinues User Access When No Longer Required",
    description: "The entity removes access when personnel leave or change roles.",
    guidance: "Create a formal offboarding checklist that revokes all system access within 24 hours of departure.",
    commonEvidence: ["Offboarding SOP", "Access revocation records", "HR termination process"],
    relatedPolicies: ["access_control", "employee_security"],
    difficulty: "medium",
    estimatedHours: 3,
  },
  {
    id: "CC6.6",
    category: "CC6",
    categoryName: "Logical and Physical Access Controls",
    title: "Measures to Prevent or Detect Unauthorized Access",
    description: "The entity implements controls to prevent or detect unauthorized access.",
    guidance: "Enable AWS CloudTrail, GitHub audit logs, and application-level audit logging. Set up anomaly alerts.",
    commonEvidence: ["CloudTrail enabled screenshot", "Audit log configuration", "Failed login alert setup"],
    relatedPolicies: ["access_control", "incident_response"],
    difficulty: "high",
    estimatedHours: 8,
  },
  {
    id: "CC6.7",
    category: "CC6",
    categoryName: "Logical and Physical Access Controls",
    title: "Encryption of Data in Transit and at Rest",
    description: "The entity restricts the transmission and movement of sensitive information.",
    guidance: "Enforce TLS 1.2+ everywhere. Encrypt database backups. Use S3 server-side encryption. Document encryption keys management.",
    commonEvidence: ["SSL certificate screenshots", "S3 encryption config", "Database encryption settings", "Key management policy"],
    relatedPolicies: ["data_classification", "access_control"],
    difficulty: "medium",
    estimatedHours: 5,
  },
  {
    id: "CC6.8",
    category: "CC6",
    categoryName: "Logical and Physical Access Controls",
    title: "Prevents or Detects Unauthorized Software",
    description: "The entity implements controls to prevent or detect unauthorized software.",
    guidance: "Use dependency scanning (Dependabot/Snyk). Have a process for reviewing third-party packages.",
    commonEvidence: ["Dependabot configuration", "Dependency audit reports", "Package approval process"],
    relatedPolicies: ["change_management"],
    difficulty: "medium",
    estimatedHours: 4,
  },

  // ─── CC7 — System Operations ─────────────────────────────────────────────────
  {
    id: "CC7.1",
    category: "CC7",
    categoryName: "System Operations",
    title: "Detects and Monitors New Vulnerabilities",
    description: "The entity identifies, develops, and implements controls to detect vulnerabilities.",
    guidance: "Run automated vulnerability scans. Subscribe to security advisories for your tech stack.",
    commonEvidence: ["Vulnerability scan reports", "Security advisory subscription", "Patching records"],
    relatedPolicies: ["change_management", "incident_response"],
    difficulty: "high",
    estimatedHours: 8,
  },
  {
    id: "CC7.2",
    category: "CC7",
    categoryName: "System Operations",
    title: "Monitors System Components for Anomalies",
    description: "The entity monitors system components and the operation of controls.",
    guidance: "Set up application monitoring (Sentry, Datadog, or similar). Configure alerts for error spikes and performance degradation.",
    commonEvidence: ["Monitoring dashboard", "Alert configuration", "On-call runbook"],
    relatedPolicies: ["incident_response"],
    difficulty: "medium",
    estimatedHours: 6,
  },
  {
    id: "CC7.3",
    category: "CC7",
    categoryName: "System Operations",
    title: "Evaluates Security Events",
    description: "The entity evaluates security events to determine whether they are incidents.",
    guidance: "Document your security event triage process. Define what constitutes an incident requiring escalation.",
    commonEvidence: ["Incident classification matrix", "Security event log", "Triage runbook"],
    relatedPolicies: ["incident_response"],
    difficulty: "medium",
    estimatedHours: 4,
  },
  {
    id: "CC7.4",
    category: "CC7",
    categoryName: "System Operations",
    title: "Responds to Identified Security Incidents",
    description: "The entity responds to identified security incidents.",
    guidance: "Create a formal incident response plan with roles, escalation paths, and communication templates.",
    commonEvidence: ["Incident response plan", "IR contact list", "Post-incident review template"],
    relatedPolicies: ["incident_response"],
    difficulty: "high",
    estimatedHours: 8,
  },
  {
    id: "CC7.5",
    category: "CC7",
    categoryName: "System Operations",
    title: "Identifies Disclosure Requirements for Security Incidents",
    description: "The entity identifies and responds to disclosure requirements for security incidents.",
    guidance: "Know your breach notification obligations (state laws, GDPR if applicable). Have notification templates ready.",
    commonEvidence: ["Breach notification policy", "Notification templates", "Legal requirements summary"],
    relatedPolicies: ["incident_response", "data_classification"],
    difficulty: "medium",
    estimatedHours: 4,
  },

  // ─── CC8 — Change Management ─────────────────────────────────────────────────
  {
    id: "CC8.1",
    category: "CC8",
    categoryName: "Change Management",
    title: "Authorizes, Designs, Develops, Configures, Documents, Tests, and Approves Infrastructure and Software Changes",
    description: "The entity authorizes, designs, develops, configures, documents, tests, and approves changes.",
    guidance: "Use pull requests with required reviews. Maintain a changelog. Deploy to staging before production. Use feature flags for risky changes.",
    commonEvidence: ["PR review policy", "Deployment runbook", "Staging environment evidence", "Release notes"],
    relatedPolicies: ["change_management"],
    difficulty: "medium",
    estimatedHours: 6,
  },

  // ─── CC9 — Risk Mitigation ────────────────────────────────────────────────────
  {
    id: "CC9.1",
    category: "CC9",
    categoryName: "Risk Mitigation",
    title: "Identifies, Selects, and Develops Risk Mitigation Activities",
    description: "The entity identifies and develops risk mitigation activities.",
    guidance: "For each risk in your risk register, document your mitigation strategy (accept, avoid, transfer, reduce).",
    commonEvidence: ["Risk mitigation plan", "Risk register with mitigations", "Insurance documentation"],
    relatedPolicies: ["risk_assessment"],
    difficulty: "medium",
    estimatedHours: 5,
  },
  {
    id: "CC9.2",
    category: "CC9",
    categoryName: "Risk Mitigation",
    title: "Assesses and Manages Risks from Vendors and Business Partners",
    description: "The entity assesses and manages risks associated with vendors and business partners.",
    guidance: "Maintain a vendor risk register. Review subprocessors annually. Ensure DPAs are in place for data processors.",
    commonEvidence: ["Vendor risk register", "DPA records", "Vendor security questionnaire responses"],
    relatedPolicies: ["vendor_management"],
    difficulty: "medium",
    estimatedHours: 5,
  },

  // ─── A1 — Availability ────────────────────────────────────────────────────────
  {
    id: "A1.1",
    category: "A1",
    categoryName: "Availability",
    title: "Maintains Minimum Necessary Components to Support Current and Expected Capacity Requirements",
    description: "The entity maintains system components to support availability.",
    guidance: "Document your infrastructure capacity planning. Show how you scale to meet demand.",
    commonEvidence: ["Infrastructure diagram", "Auto-scaling configuration", "Capacity planning document"],
    relatedPolicies: ["business_continuity"],
    difficulty: "medium",
    estimatedHours: 5,
  },
  {
    id: "A1.2",
    category: "A1",
    categoryName: "Availability",
    title: "Implements Backup and Recovery Procedures",
    description: "The entity implements backup and recovery procedures.",
    guidance: "Configure automated database backups. Test restore procedures quarterly. Document your RPO and RTO targets.",
    commonEvidence: ["Backup configuration screenshots", "Recovery test records", "RTO/RPO documentation"],
    relatedPolicies: ["business_continuity"],
    difficulty: "high",
    estimatedHours: 8,
  },
  {
    id: "A1.3",
    category: "A1",
    categoryName: "Availability",
    title: "Tests Recovery Plan Objectives",
    description: "The entity tests recovery plan objectives to ensure objectives are met.",
    guidance: "Run at least one disaster recovery test per year. Document the results and any gaps found.",
    commonEvidence: ["DR test plan", "DR test results", "Post-test remediation records"],
    relatedPolicies: ["business_continuity"],
    difficulty: "high",
    estimatedHours: 10,
  },
];

export const CONTROL_CATEGORIES = [
  { id: "CC1", name: "Control Environment", count: 5 },
  { id: "CC2", name: "Communication and Information", count: 3 },
  { id: "CC3", name: "Risk Assessment", count: 4 },
  { id: "CC4", name: "Monitoring Activities", count: 2 },
  { id: "CC5", name: "Control Activities", count: 3 },
  { id: "CC6", name: "Logical and Physical Access Controls", count: 8 },
  { id: "CC7", name: "System Operations", count: 5 },
  { id: "CC8", name: "Change Management", count: 1 },
  { id: "CC9", name: "Risk Mitigation", count: 2 },
  { id: "A1", name: "Availability", count: 3 },
] as const;

export function getControlById(id: string): SOC2Control | undefined {
  return SOC2_CONTROLS.find((c) => c.id === id);
}

export function getControlsByCategory(category: string): SOC2Control[] {
  return SOC2_CONTROLS.filter((c) => c.category === category);
}
